:root{
  --navy:#0b2f5b;--navy-2:#123f73;--blue:#0f6f9f;--cyan:#e9f5fa;--paper:#f5f7fa;
  --card:#fff;--ink:#10243e;--muted:#66768a;--line:#dbe3ec;--good:#147a55;--good-bg:#eaf7f1;
  --bad:#b42318;--bad-bg:#fff0ee;--warn:#9a6700;--warn-bg:#fff8df;--shadow:0 12px 30px rgba(17,44,78,.08);
  --radius:18px;--safe-bottom:env(safe-area-inset-bottom,0px)
}
*{box-sizing:border-box}html{background:var(--paper);color:var(--ink);font-family:"Noto Sans SC","PingFang SC","Microsoft YaHei",system-ui,sans-serif}body{margin:0;min-height:100vh;background:linear-gradient(180deg,#edf4f9 0,#f7f8fa 240px)}button,input{font:inherit}button{cursor:pointer}.hidden{display:none!important}
.topbar{position:sticky;top:0;z-index:20;height:72px;display:flex;align-items:center;justify-content:space-between;padding:10px max(18px,calc((100vw - 1120px)/2));background:rgba(247,249,251,.92);backdrop-filter:blur(16px);border-bottom:1px solid rgba(219,227,236,.85)}
.brand{display:flex;align-items:center;gap:12px;border:0;background:transparent;text-align:left;color:var(--ink);padding:0}.brand-mark{width:42px;height:42px;border-radius:12px;display:grid;place-items:center;background:var(--navy);color:#fff;font-weight:800;font-size:14px;letter-spacing:.5px;box-shadow:0 6px 18px rgba(11,47,91,.22)}.brand strong{display:block;font-size:16px}.brand small{display:block;color:var(--muted);font-size:11px;margin-top:2px}.top-actions{display:flex;gap:8px;align-items:center}.ghost-btn,.icon-btn{border:1px solid var(--line);background:#fff;color:var(--navy);border-radius:12px;padding:9px 14px;font-weight:700}.icon-btn{width:42px;padding:9px 0;font-size:18px}
main{max-width:1120px;margin:0 auto;padding:26px 20px calc(100px + var(--safe-bottom));outline:none}.bottom-nav{display:none}
.hero{background:linear-gradient(135deg,var(--navy),#174e86);color:#fff;border-radius:24px;padding:28px;box-shadow:0 18px 40px rgba(11,47,91,.18);position:relative;overflow:hidden}.hero:after{content:"";position:absolute;width:260px;height:260px;border-radius:50%;right:-100px;top:-120px;background:rgba(255,255,255,.08)}.hero h1{margin:0 0 8px;font-size:28px}.hero p{margin:0;color:rgba(255,255,255,.78);max-width:620px;line-height:1.7}.hero-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:22px}.primary-btn,.secondary-btn,.danger-btn{border:0;border-radius:13px;padding:12px 17px;font-weight:800}.primary-btn{background:#fff;color:var(--navy)}.primary-btn.dark{background:var(--navy);color:#fff}.secondary-btn{background:#edf3f8;color:var(--navy);border:1px solid #cddbe8}.danger-btn{background:var(--bad-bg);color:var(--bad);border:1px solid #f5c8c2}.hero .secondary-btn{background:rgba(255,255,255,.12);color:#fff;border:1px solid rgba(255,255,255,.25)}
.stats-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:18px 0}.stat-card,.panel,.chapter-card,.question-card,.resume-card{background:var(--card);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow)}.stat-card{padding:18px}.stat-card span{display:block;color:var(--muted);font-size:13px}.stat-card strong{display:block;font-size:27px;margin-top:5px}.stat-card small{color:var(--muted)}
.section-head{display:flex;align-items:end;justify-content:space-between;gap:12px;margin:28px 0 14px}.section-head h2{margin:0;font-size:21px}.section-head p{margin:3px 0 0;color:var(--muted);font-size:13px}.link-btn{border:0;background:transparent;color:var(--blue);font-weight:800;padding:6px}
.chapter-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.chapter-card{padding:19px;transition:.2s}.chapter-card:hover{transform:translateY(-2px);border-color:#b9ccdd}.chapter-card button{border:0;background:transparent;padding:0;text-align:left;width:100%;color:inherit}.chapter-index{font-size:11px;font-weight:900;letter-spacing:1px;color:var(--blue)}.chapter-card h3{margin:7px 0 10px;font-size:19px}.meta-row{display:flex;gap:10px;flex-wrap:wrap;color:var(--muted);font-size:12px}.progress{height:8px;background:#edf1f5;border-radius:99px;overflow:hidden;margin:14px 0 8px}.progress>i{display:block;height:100%;background:linear-gradient(90deg,var(--blue),#58a9ca);border-radius:99px}.chapter-bottom{display:flex;justify-content:space-between;font-size:12px;color:var(--muted)}
.resume-card{margin:18px 0;padding:16px 18px;display:flex;align-items:center;justify-content:space-between;gap:16px;border-left:5px solid var(--blue)}.resume-card h3{margin:0 0 4px;font-size:16px}.resume-card p{margin:0;color:var(--muted);font-size:13px}.resume-actions{display:flex;gap:8px;flex-shrink:0}
.page-head{display:flex;justify-content:space-between;align-items:flex-start;gap:18px;margin-bottom:18px}.page-head h1{margin:0 0 6px;font-size:27px}.page-head p{margin:0;color:var(--muted)}.back-btn{border:0;background:transparent;color:var(--blue);font-weight:800;padding:0 0 12px}.panel{padding:20px;margin:14px 0}.panel h2,.panel h3{margin:0 0 12px}.mode-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.mode-card{border:1px solid var(--line);background:#fff;border-radius:15px;padding:16px;text-align:left;color:var(--ink)}.mode-card:hover{border-color:#9ebbd2}.mode-card strong{display:block}.mode-card small{display:block;color:var(--muted);margin-top:5px;line-height:1.45}.mode-card[disabled]{opacity:.45;cursor:not-allowed}
.filter-row{display:flex;gap:8px;flex-wrap:wrap}.chip{border:1px solid var(--line);background:#fff;color:var(--muted);border-radius:999px;padding:8px 13px;font-size:13px}.chip.active{background:var(--navy);color:#fff;border-color:var(--navy)}
.question-list{display:grid;gap:10px}.question-row{display:grid;grid-template-columns:auto 1fr auto;gap:12px;align-items:start;border:1px solid var(--line);background:#fff;border-radius:14px;padding:13px}.q-no{width:30px;height:30px;border-radius:9px;background:#edf4fa;color:var(--navy);display:grid;place-items:center;font-weight:900;font-size:12px}.q-summary{font-size:14px;line-height:1.55}.q-summary small{display:block;color:var(--muted);margin-top:5px}.status-dot{font-size:12px;border-radius:999px;padding:5px 8px;background:#eef2f6;color:var(--muted)}.status-dot.wrong{background:var(--bad-bg);color:var(--bad)}.status-dot.done{background:var(--good-bg);color:var(--good)}
.practice-shell{max-width:820px;margin:0 auto}.practice-top{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.practice-top h1{font-size:18px;margin:0}.practice-top p{margin:3px 0 0;color:var(--muted);font-size:12px}.practice-actions{display:flex;gap:8px}.practice-progress{margin-bottom:14px}.question-card{padding:24px}.question-meta{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:14px}.badge{display:inline-flex;align-items:center;border-radius:999px;padding:6px 10px;font-size:12px;font-weight:800;background:#eaf3f8;color:var(--blue)}.badge.multi{background:#f2edff;color:#6840a5}.badge.wrong{background:var(--bad-bg);color:var(--bad)}.star-btn{border:1px solid var(--line);background:#fff;border-radius:11px;width:42px;height:38px;color:#9a6c00;font-size:19px}.star-btn.active{background:#fff7d6;border-color:#e8cc69}.question-card h2{font-size:20px;line-height:1.65;margin:0 0 18px;font-weight:750}.prompt{font-size:13px;color:var(--blue);font-weight:800;margin-bottom:8px}.options{display:grid;gap:10px}.option{display:grid;grid-template-columns:36px 1fr;align-items:start;gap:10px;border:1px solid var(--line);background:#fff;border-radius:14px;padding:13px;text-align:left;color:var(--ink);line-height:1.55}.option:hover{border-color:#9abbd3;background:#fbfdff}.option-key{width:30px;height:30px;border-radius:9px;background:#edf2f6;display:grid;place-items:center;font-weight:900;color:var(--navy)}.option.selected{border-color:var(--blue);background:#eef8fc}.option.selected .option-key{background:var(--blue);color:#fff}.option.correct{border-color:#74bd9d;background:var(--good-bg)}.option.correct .option-key{background:var(--good);color:#fff}.option.incorrect{border-color:#ee9d94;background:var(--bad-bg)}.option.incorrect .option-key{background:var(--bad);color:#fff}.option[disabled]{cursor:default}
.answer-panel{margin-top:17px;border-radius:14px;padding:15px 16px;line-height:1.65}.answer-panel.good{background:var(--good-bg);border:1px solid #b8e1cf}.answer-panel.bad{background:var(--bad-bg);border:1px solid #f2c2bc}.answer-panel strong{display:block;margin-bottom:4px}.note-box{margin-top:10px;padding-top:10px;border-top:1px dashed rgba(16,36,62,.2);font-size:13px}.practice-footer{display:flex;justify-content:space-between;gap:10px;margin-top:18px}.practice-footer>div{display:flex;gap:8px}.submit-btn{min-width:126px}
.empty{padding:38px 20px;text-align:center;color:var(--muted)}.empty strong{display:block;color:var(--ink);font-size:18px;margin-bottom:7px}.wrong-grid{display:grid;gap:10px}.wrong-item{border:1px solid var(--line);background:#fff;border-radius:14px;padding:15px;display:grid;grid-template-columns:1fr auto;gap:14px}.wrong-item h3{margin:0;font-size:15px;line-height:1.5}.wrong-item p{margin:6px 0 0;color:var(--muted);font-size:12px}.streak{font-weight:800;color:var(--blue);white-space:nowrap}.mastery-dots{display:inline-flex;gap:4px;margin-left:6px}.mastery-dots i{width:8px;height:8px;border-radius:50%;background:#d8e0e7}.mastery-dots i.on{background:var(--good)}
.data-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.data-block{border:1px solid var(--line);border-radius:15px;padding:17px;background:#fff}.data-block h3{margin:0 0 7px}.data-block p{margin:0 0 14px;color:var(--muted);font-size:13px;line-height:1.6}.button-row{display:flex;gap:8px;flex-wrap:wrap}.storage-status{display:flex;gap:8px;align-items:center;margin:10px 0 14px}.storage-status b{font-size:13px}.dot{width:9px;height:9px;border-radius:50%;background:#9ca8b3}.dot.ok{background:var(--good)}.notice{background:var(--warn-bg);border:1px solid #eedb91;color:#6f5200;border-radius:14px;padding:13px 15px;font-size:13px;line-height:1.6;margin:12px 0}
.summary{max-width:700px;margin:20px auto}.summary-score{text-align:center;padding:26px}.summary-score strong{font-size:46px;color:var(--navy)}.summary-score p{color:var(--muted)}.summary-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:14px 0}.summary-grid div{background:#f2f5f8;border-radius:13px;padding:14px;text-align:center}.summary-grid b{display:block;font-size:21px}.summary-actions{display:flex;justify-content:center;gap:10px;flex-wrap:wrap}
.toast{position:fixed;left:50%;bottom:28px;z-index:100;transform:translate(-50%,24px);opacity:0;pointer-events:none;background:#14263c;color:#fff;border-radius:12px;padding:11px 16px;font-size:13px;box-shadow:0 10px 25px rgba(0,0,0,.18);transition:.2s}.toast.show{opacity:1;transform:translate(-50%,0)}.modal-backdrop{position:fixed;inset:0;z-index:80;background:rgba(5,20,38,.48);display:grid;place-items:center;padding:20px}.modal{width:min(520px,100%);background:#fff;border-radius:20px;padding:22px;box-shadow:0 30px 70px rgba(0,0,0,.25)}.modal h2{margin:0 0 9px}.modal p{color:var(--muted);line-height:1.65}.modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}
@media(max-width:820px){.stats-grid{grid-template-columns:1fr 1fr}.mode-grid{grid-template-columns:1fr 1fr}.chapter-grid{grid-template-columns:1fr}.data-grid{grid-template-columns:1fr}.topbar{height:64px;padding:9px 14px}.brand small{display:none}main{padding:20px 14px calc(92px + var(--safe-bottom))}.bottom-nav{display:grid;grid-template-columns:repeat(4,1fr);position:fixed;z-index:30;left:0;right:0;bottom:0;padding:6px 8px calc(6px + var(--safe-bottom));background:rgba(255,255,255,.96);backdrop-filter:blur(16px);border-top:1px solid var(--line)}.bottom-nav button{border:0;background:transparent;color:var(--muted);display:grid;place-items:center;gap:2px;padding:4px}.bottom-nav span{font-size:20px;height:22px}.bottom-nav em{font-style:normal;font-size:10px}.bottom-nav button.active{color:var(--navy);font-weight:800}.hero{padding:22px}.hero h1{font-size:24px}.question-card{padding:18px}.question-card h2{font-size:18px}.practice-top{align-items:flex-start}.resume-card{align-items:flex-start;flex-direction:column}.page-head{flex-direction:column}.wrong-item{grid-template-columns:1fr}.toast{bottom:90px}.summary-grid{grid-template-columns:repeat(3,1fr)}}
@media(max-width:480px){.mode-grid{grid-template-columns:1fr}.practice-footer{align-items:stretch}.practice-footer>div{display:grid;grid-template-columns:1fr 1fr}.practice-footer{display:grid}.submit-btn{width:100%}.stats-grid{gap:9px}.stat-card{padding:14px}.stat-card strong{font-size:23px}.option{grid-template-columns:32px 1fr;padding:11px}.brand strong{font-size:15px}}
